### ISSUE TITLE
Incorrect field name spend_output_index in the CloudFormation template

### ISSUE THREAD

**Issue by irajan88** [aws-samples/digital-assets-examples#7]
The below CF template contains the schema for the BTC transaction table. As per the template, the field "input" in the transaction table contains "spend_output_index".

https://github.com/aws-solutions-library-samples/guidance-for-digital-assets-on-aws/blob/fd2310503135df6210c4134b50b8a2cccaf0d8e7/analytics/consumer/aws-public-blockchain.yaml#L181

When checking the source data in the S3 bucket, it can be seen that the name of the field is "spent_output_index" (not "spend_output_index").

S3 bucket URI for transaction table: s3://aws-public-blockchain/v1.0/btc/transactions/

It can also be verified in the below code section:

https://github.com/aws-solutions-library-samples/guidance-for-digital-assets-on-aws/blob/fd2310503135df6210c4134b50b8a2cccaf0d8e7/analytics/producer/copilot/bitcoin-worker/worker.py#L331C1-L333C32

I have verified the same by updating the template and testing in my AWS account. I am getting the desired result after updating the above mentioned line in the CloudFormation template.

**Comment by brrav** [comment]
merged changes
